acme_payment_homepage:
    pattern:  /payment
    defaults: { _controller: AcmePaymentBundle:Default:index }
    
acme_payment_prepare_simple_purchase_paypal_express_checkout:
    pattern:  /payment/simple_purchase/paypal_express_checkout/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchasePaypalExpressCheckout:prepare }
    
acme_payment_prepare_simple_purchase_paypal_express_checkout_doctrine:
    pattern:  /payment/simple_purchase/paypal_express_checkout/prepareDoctrine
    defaults: { _controller: AcmePaymentBundle:SimplePurchasePaypalExpressCheckout:prepareDoctrine }

acme_payment_prepare_digital_goods_simple_purchase_paypal_express_checkout:
    pattern:  /payment/simple_purchase/paypal_express_checkout/prepare_digital_goods
    defaults: { _controller: AcmePaymentBundle:SimplePurchasePaypalExpressCheckout:prepareDigitalGoods }

acme_payment_prepare_simple_purchase_authorize_net:
    pattern:  /payment/simple_purchase/authorize_net/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchaseAuthorizeNetAim:prepare }
    
acme_payment_prepare_simple_purchase_be2bill:
    pattern:  /payment/simple_purchase/be2bill/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchaseBe2Bill:prepare }
    
acme_payment_prepare_simple_purchase_paypal_express_via_omnipay:
    pattern:  /payment/simple_purchase/paypal_express_via_omnipay/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchasePaypalExpressViaOmnipay:prepare }
    
acme_payment_capture_simple:
    pattern:  /payment/simple_purchase/{contextName}/capture/{model}
    defaults: { _controller: AcmePaymentBundle:Capture:simpleCapture }